### ISSUE TITLE
3D doesn't work with react-native 0.44

### ISSUE THREAD

**Issue by belliAndrea** [jmurzy/react-native-foldview#17]
Hi, 
i've installed your lib in an app with rect-native 0.44 and it works, but the animations are all flat.
It's like the 3d effect doesn't work at all. I've even tried to install the 0.44 into your Simple project and i had the same result.
is there a way to fix it without rollback to previous react-native version?

**Comment by ronal2do** [comment]
Any update about this?

**Comment by ErrorPro** [comment]
It seems like perspective no longer works along with matrix. Now we probably need to multiply the result matrix by perspective matrix.

**Comment by jmurzy** [comment]
We need to refactor things a little to make it compatible with the latest React Native. Not sure what changed in the underlying React Native code to cause this but if you find out, feel free to send a pull request. Thanks.

**Comment by ErrorPro** [comment]
This [PR](https://github.com/jmurzy/react-native-foldview/issues/17) fixes it, but the example still doesn't work for the latest RN. I can push my changes which fix that too, but it would be a huge PR :)

**Comment by jmurzy** [comment]
Thanks @ErrorPro! Please send in the PR regardless of how huge it is. That'd make a sizable contribution, so feel free to also add yourself to the contributors list in package.json.
