### ISSUE TITLE
example Simple Invalid layout RCTView error

### ISSUE THREAD

**Issue by jasan-s** [jmurzy/react-native-foldview#18]
The example simple otuputs an Invalid Layout error at build

**Comment by sobstel** [comment]
Same here.

<img width="374" alt="screen shot 2017-07-28 at 14 32 54" src="https://user-images.githubusercontent.com/117428/28717348-b840d51a-73a1-11e7-86d7-c6e69510d632.png">

**Comment by ghost** [comment]
I can build it, but nothign happens when I press the cards.

**Comment by ItsNoHax** [comment]
Because it doesn't work on Android, it says on the readme

**Comment by creative-git** [comment]
same here , flip function  is not triggered at all

**Comment by jmurzy** [comment]
Probably caused by a React Native version mismatch. We need to refactor things a little to make it compatible with the latest React Native. Feel free to send a pull request. Thanks.
