### ISSUE TITLE
PR: Add support for `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [jmurzy/react-native-foldview#2]
This plugin allows flow to be run as an eslint plugin 🎉 Would a PR for this be welcome?

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by jmurzy** [comment]
Neat! 

We'd need to type the project with Flow first. I won't be able to work on adding the annotations anytime soon but I'd be willing to accept a PR if you're up for it.

🍺

**Comment by amilajack** [comment]
Where are the annotations need? In the example or in the src or both?

**Comment by jmurzy** [comment]
I'd say src is good enough. Ideally, we keep the example as is. Not everyone is familiar with flow.

Thanks! 💯

**Comment by amilajack** [comment]
Closing, as I made the PR for this
