### ISSUE TITLE
this.updater.enqueueCallback is not a function

### ISSUE THREAD

**Issue by devLaaziz** [jmurzy/react-native-foldview#21]
![simulator screen shot 6 oct 2017 a 14 50 44](https://user-images.githubusercontent.com/12499618/31280888-c643c93e-aaa5-11e7-87de-7ff2908b40cb.png)

**Comment by jmurzy** [comment]
We probably need to refactor things a little to make it compatible with the latest React Native. Feel free to send a pull request. Thanks.
