### ISSUE TITLE
PropTypes are not part of React anymore

### ISSUE THREAD

**Issue by ma-pe** [jmurzy/react-native-foldview#23]
First of all: Awesome Work!

Your library isn't compatible to newer React-Versions, since PropTypes isn't part of React anymore.

You will need to import it directly now:

`import PropTypes from 'prop-types';`

**Comment by hwnprsd** [comment]
Any active maintainers?

**Comment by aithashi** [comment]
@ma-pe hi, after resolving all those version compatible problems, now am able to see blank screen without any errors. Any idea about this?

**Comment by ma-pe** [comment]
For the moment I moved away from using this library in my app, so sorry: I can't be of much help here.

**Comment by aithashi** [comment]
Thank you for your time!

**Comment by jmurzy** [comment]
This should be addressed by #25. Thanks for your patience.
