### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by rborn** [jmurzy/react-native-foldview#6]
On android the view doesn't fully unfold, and the animation it's more like a jump.
I wonder if it's an underlaying Animated issue?

PS. I'm only starting with RN 😄 
![rnfoldview](https://cloud.githubusercontent.com/assets/406409/20607159/54ab7a24-b276-11e6-9620-662324ae4bd6.gif)

Thank you.

**Comment by jmurzy** [comment]
Thanks for the issue. As also mentioned in the README, Android cannot be supported until better `overflow` support for Android lands in React Native.

> ### Platform Support
> This library heavily depends on the `overflow` style property. Unfortunately, `overflow` defaults to `hidden` on Android and cannot be changed. Although it looks like a [possible fix](https://github.com/facebook/react-native/issues/3198#issuecomment-241867280) is in the making, currently, FoldingView is only supported on iOS.

**Comment by srichallamalla935** [comment]
I am still facing issue in android the view doesn't fully unfold completely,if anyone of you  fixed it please help me out 

react-native:-0.61.4
react-native-foldview:-^1.2.1
